export default {
    CLEAR_CANVAS: 'CLEAR_CANVAS',
    RESIZE_CANVAS: 'RESIZE_CANVAS',
    SAVE_DATA: 'SAVE_DATA',
    DRAW_SIZE: 'DRAW_SIZE',
    DRAW_SIZE_UP: 'DRAW_SIZE_UP',
    DRAW_SIZE_DOWN: 'DRAW_SIZE_DOWN',
    SET_COLOR: 'SET_COLOR',
    RELOAD_PREVIEW: 'RELOAD_PREVIEW',
}